<?php

namespace Proxies\__CG__\Support\SupportBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DocmanUser extends \Support\SupportBundle\Entity\DocmanUser implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'name', 'email', 'username', 'password', 'movil', 'interno', 'ci', 'datereg', 'lastaccess', 'state', 'type', 'telefono', 'direccion', 'telefref', 'numseguro', 'cargo', 'fechanac', 'ip', 'dependeDe', 'foto', 'soporte', 'fechaModif', 'ip2', 'externo', 'oficina');
        }

        return array('__isInitialized__', 'id', 'name', 'email', 'username', 'password', 'movil', 'interno', 'ci', 'datereg', 'lastaccess', 'state', 'type', 'telefono', 'direccion', 'telefref', 'numseguro', 'cargo', 'fechanac', 'ip', 'dependeDe', 'foto', 'soporte', 'fechaModif', 'ip2', 'externo', 'oficina');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DocmanUser $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovil($movil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovil', array($movil));

        return parent::setMovil($movil);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovil', array());

        return parent::getMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterno($interno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterno', array($interno));

        return parent::setInterno($interno);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterno', array());

        return parent::getInterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setCi($ci)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCi', array($ci));

        return parent::setCi($ci);
    }

    /**
     * {@inheritDoc}
     */
    public function getCi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCi', array());

        return parent::getCi();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatereg($datereg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatereg', array($datereg));

        return parent::setDatereg($datereg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatereg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatereg', array());

        return parent::getDatereg();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastaccess($lastaccess)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastaccess', array($lastaccess));

        return parent::setLastaccess($lastaccess);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastaccess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastaccess', array());

        return parent::getLastaccess();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', array($telefono));

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', array());

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', array($direccion));

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', array());

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefref($telefref)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefref', array($telefref));

        return parent::setTelefref($telefref);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefref()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefref', array());

        return parent::getTelefref();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumseguro($numseguro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumseguro', array($numseguro));

        return parent::setNumseguro($numseguro);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumseguro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumseguro', array());

        return parent::getNumseguro();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo($cargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', array($cargo));

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', array());

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechanac($fechanac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechanac', array($fechanac));

        return parent::setFechanac($fechanac);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechanac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechanac', array());

        return parent::getFechanac();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp($ip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp', array($ip));

        return parent::setIp($ip);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp', array());

        return parent::getIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setDependeDe($dependeDe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDependeDe', array($dependeDe));

        return parent::setDependeDe($dependeDe);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependeDe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependeDe', array());

        return parent::getDependeDe();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', array($foto));

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setSoporte($soporte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoporte', array($soporte));

        return parent::setSoporte($soporte);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoporte', array());

        return parent::getSoporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModif($fechaModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModif', array($fechaModif));

        return parent::setFechaModif($fechaModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModif', array());

        return parent::getFechaModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setIp2($ip2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIp2', array($ip2));

        return parent::setIp2($ip2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIp2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIp2', array());

        return parent::getIp2();
    }

    /**
     * {@inheritDoc}
     */
    public function setExterno($externo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExterno', array($externo));

        return parent::setExterno($externo);
    }

    /**
     * {@inheritDoc}
     */
    public function getExterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExterno', array());

        return parent::getExterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setOficina(\Support\SupportBundle\Entity\DocmanOficina $oficina = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOficina', array($oficina));

        return parent::setOficina($oficina);
    }

    /**
     * {@inheritDoc}
     */
    public function getOficina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOficina', array());

        return parent::getOficina();
    }

}
